#!/bin/bash
# This script creates an advanced .asoundrc file to provide a stable, boosted microphone.

set -e

echo "🔊 Creating stable and boosted ALSA device configuration..."

SPEAKER_CARD=$(aplay -l | grep "AUREON XFIRE8.0 HD" | sed -n 's/card \([0-9]*\):.*/\1/p' | head -n 1)
MIC_CARD=$(arecord -l | grep "USB PnP Sound Device" | sed -n 's/card \([0-9]*\):.*/\1/p' | head -n 1)

if [ -z "$SPEAKER_CARD" ]; then
    echo "❌ Error: Could not find the AUREON XFIRE8.0 HD sound card." && exit 1
fi

if [ -z "$MIC_CARD" ]; then
    echo "❌ Error: Could not find the USB PnP Sound Device microphone." && exit 1
fi

echo "✅ Found Speaker (AUREON) at card: $SPEAKER_CARD"
echo "✅ Found Microphone (USB PnP) at card: $MIC_CARD"

# Create the .asoundrc file with a softvol plugin for microphone boost.
cat > ~/.asoundrc << EOL
# ALSA configuration for KidPrinter with Microphone Boost
# Automatically generated by create_asoundrc.sh

# -- Raw Hardware Devices --
# These are direct pointers to the hardware.
pcm.kidprinter_playback_hw {
    type hw
    card $SPEAKER_CARD
    device 0
}

pcm.kidprinter_mic_hw {
    type hw
    card $MIC_CARD
    device 0
}

# -- Microphone Boost Configuration --
# 1. Create a software volume control plugin.
# This creates a new mixer control called "Mic Boost Volume".
pcm.mic_softvol {
    type softvol
    slave.pcm "kidprinter_mic_hw"
    control {
        name "Mic Boost Volume"
        card $MIC_CARD
    }
    min_dB -3.0
    max_dB 30.0 # Allow up to 30dB of software gain
}

# -- Final, Usable Devices --
# These are the devices applications should use.

# Playback device (no changes needed)
pcm.kidprinter_playback {
    type plug
    slave.pcm "kidprinter_playback_hw"
}

# Boosted microphone device
# We use a plug here to handle any necessary conversions.
pcm.kidprinter_mic {
    type plug
    slave.pcm "mic_softvol"
}

# -- Default Device Configuration --
# Set our boosted mic and playback as the system default.
pcm.!default {
    type asym
    playback.pcm "kidprinter_playback"
    capture.pcm "kidprinter_mic"
}

ctl.!default {
    type hw
    card $SPEAKER_CARD
}
EOL

# Set the default boost level after creating the config
# We need to wait a moment for the new device to be recognized.
sleep 1

# Use amixer to set the new "Mic Boost Volume" control to 20dB.
# The control is on the same card as the physical mic.
if amixer -c $MIC_CARD sget 'Mic Boost Volume' > /dev/null; then
    amixer -c $MIC_CARD sset 'Mic Boost Volume' 20dB > /dev/null
    echo "✅ Set Mic Boost Volume to 20dB."
else
    echo "⚠️ Could not set Mic Boost Volume. You may need to set it manually via alsamixer."
fi

echo "✅ Successfully created ~/.asoundrc with boosted microphone."
echo "   - Playback device is named: kidprinter_playback"
echo "   - Microphone device is named: kidprinter_mic (with boost)"
