#!/bin/bash
# This script creates a .asoundrc file to provide stable names for audio devices.

# Exit immediately if a command exits with a non-zero status.
set -e

echo "🔊 Creating stable ALSA device configuration..."

# Find the card number for the AUREON XFIRE8.0 HD (playback)
# We use grep to find the line with the name, then cut to get the card number.
SPEAKER_CARD=$(aplay -l | grep "AUREON XFIRE8.0 HD" | sed -n 's/card \([0-9]*\):.*/\1/p' | head -n 1)

# Find the card number for the USB PnP Sound Device (microphone)
MIC_CARD=$(arecord -l | grep "USB PnP Sound Device" | sed -n 's/card \([0-9]*\):.*/\1/p' | head -n 1)

# Check if we found the cards
if [ -z "$SPEAKER_CARD" ]; then
    echo "❌ Error: Could not find the AUREON XFIRE8.0 HD sound card."
    echo "Please make sure it is connected and run 'aplay -l' to verify."
    exit 1
fi

if [ -z "$MIC_CARD" ]; then
    echo "❌ Error: Could not find the USB PnP Sound Device microphone."
    echo "Please make sure it is connected and run 'arecord -l' to verify."
    exit 1
fi

echo "✅ Found Speaker (AUREON) at card: $SPEAKER_CARD"
echo "✅ Found Microphone (USB PnP) at card: $MIC_CARD"

# Create the .asoundrc file in the user's home directory.
# This configuration creates two new PCM devices: 'kidprinter_playback' and 'kidprinter_mic'
# These names will now be permanently mapped to the correct hardware.
cat > ~/.asoundrc << EOL
# ALSA configuration for KidPrinter
# Automatically generated by create_asoundrc.sh

pcm.kidprinter_playback {
    type hw
    card $SPEAKER_CARD
    device 0
}

pcm.kidprinter_mic {
    type hw
    card $MIC_CARD
    device 0
    format S16_LE
    rate 48000
}

# This makes the playback device the default for applications that don't specify one.
pcm.!default {
    type asym
    playback.pcm "kidprinter_playback"
    capture.pcm "kidprinter_mic"
}

ctl.!default {
    type hw
    card $SPEAKER_CARD
}

EOL

echo "✅ Successfully created ~/.asoundrc with stable device names."
echo "   - Playback device is named: kidprinter_playback"
echo "   - Microphone device is named: kidprinter_mic"
echo "\nTo apply the changes, you may need to restart applications using ALSA."